#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 25 18:21:16 -04 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_divisor_param_behav -key {Behavioral:sim_1:Functional:test_divisor_param} -tclbatch test_divisor_param.tcl -log simulate.log"
xsim test_divisor_param_behav -key {Behavioral:sim_1:Functional:test_divisor_param} -tclbatch test_divisor_param.tcl -log simulate.log

