#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 20 09:49:24 -04 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_bench_sum_behav -key {Behavioral:sim_1:Functional:test_bench_sum} -tclbatch test_bench_sum.tcl -view /home/aalva/Laboratorio_1/test_muxs_behav.wcfg -log simulate.log"
xsim test_bench_sum_behav -key {Behavioral:sim_1:Functional:test_bench_sum} -tclbatch test_bench_sum.tcl -view /home/aalva/Laboratorio_1/test_muxs_behav.wcfg -log simulate.log

